# Generated by Django 4.2.29 on 2026-06-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Borrowing_user_id', models.IntegerField()),
                ('Borrowing_item_id', models.IntegerField()),
                ('Borrow_duration', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=255)),
                ('Item_desc', models.CharField(max_length=255)),
                ('Item_id', models.IntegerField()),
                ('Item_borrowed_state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Lended_items_id', models.JSONField(default=list)),
                ('User_Id', models.IntegerField()),
            ],
        ),
    ]
