# Generated by Django 4.2.29 on 2026-06-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lend', '0002_alter_users_lended_items_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
