# Generated by Django 4.2.29 on 2026-06-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lend', '0003_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_request',
            name='Borrow_acceptance',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='Item_post_date',
            field=models.DateField(null=True),
        ),
    ]
