# Generated by Django 4.2.29 on 2026-06-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lend', '0004_borrow_request_borrow_acceptance_item_item_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='User_Id',
        ),
    ]
