# Generated by Django 4.2.29 on 2026-06-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lend', '0005_remove_users_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Borrowed_items_id',
            field=models.JSONField(default=list, null=True),
        ),
    ]
