# Generated by Django 4.2.29 on 2026-06-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lend', '0006_users_borrowed_items_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Item_id',
        ),
    ]
