# Generated by Django 4.2.29 on 2026-06-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lend', '0007_remove_item_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error_reporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_usr', models.IntegerField()),
                ('report', models.CharField(max_length=255)),
            ],
        ),
    ]
