# Generated by Django 4.2.29 on 2026-06-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lend', '0008_error_reporting'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_request',
            name='user_Borrowing_from_id',
            field=models.IntegerField(null=True),
        ),
    ]
