# Generated by Django 4.2.29 on 2026-06-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lend', '0009_borrow_request_user_borrowing_from_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow_request',
            name='Borrow_duration',
        ),
    ]
