# Generated by Django 4.2.29 on 2026-06-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lend', '0010_remove_borrow_request_borrow_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Item_desc',
            field=models.CharField(max_length=1200),
        ),
    ]
