# Generated by Django 4.2.29 on 2026-06-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lend', '0011_alter_item_item_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Item_post_date',
        ),
    ]
