# Generated by Django 4.2.29 on 2026-07-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lend', '0012_remove_item_item_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Item_image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images'),
        ),
    ]
